spring:
  server.port: 8080

  datasource:
    url: jdbc:h2:mem:testingA2Z
    username: sa
    password: password

  jpa:
    generate-ddl: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
