@startuml
!include <C4/C4_Component.puml>

left to right direction

Component(passwordCharacterType, "PasswordCharacterType", "Java", "Represents a type of character that may appear in a password.\n\nPossible values are: UPPERCASE_LETTER\nLOWERCASE_LETTER\nDIGIT\nSPECIAL\nILLEGAL")

@enduml
