@startuml
!include <C4/C4_Component.puml>

left to right direction

Component(passwordValidator, "PasswordValidator", "Java", "Validates plain text passwords. Throws exceptions for invalid passwords.")
Component(passwordCharacterType, "PasswordCharacterType", "Java", "Represents a type of character that may appear in a password.")
Component(passwordValidationError, "PasswordValidationError", "Java", "Describes a reason why password validation failed.")
Component(invalidPasswordException, "InvalidPasswordException", "Java", "An exception thrown when password is not valid, containing more information about why the validation failed.")

Rel(invalidPasswordException, passwordValidationError, "Contains")
Rel(passwordValidator, passwordCharacterType, "Determines")
Rel(passwordValidator, invalidPasswordException, "Throws")

@enduml
