@startuml
!include <C4/C4_Component.puml>

left to right direction

Component(hashedPassword, "Hashed Password", "Java", "Representation of a salted and hashed user password.")
Component(hasher, "Hasher", "Java Interface", "Interface for hashing text.")

Rel(hashedPassword, hasher, "Checks hashes using")

@enduml
