@startuml
!include <C4/C4_Component.puml>

left to right direction

Component(hashedPassword, "Hashed Password", "Java", "Representation of a salted and hashed user password.")
Component(hashedPasswordFactory, "HashedPasswordFactory", "Java", "Factory for creating new hashed passwords.")
Component(saltGenerator, "SaltGenerator", "Mock", "Interface for generating salt.")
Component(hasher, "Hasher", "Mock", "Interface for hashing text.")
Component(passwordValidator, "PasswordValidator", "Static", "Validates plain text passwords.")


Rel(hashedPassword, hasher, "Checks hashes using")
Rel(hashedPasswordFactory, hasher, "Hashes using")
Rel(hashedPasswordFactory, saltGenerator, "Generates salt using")
Rel(hashedPasswordFactory, hashedPassword, "Creates")
Rel(hashedPasswordFactory, passwordValidator, "Validates using")

@enduml
